---
aliases: [digital-toolset]
#projects: [up-running-blogdown] # links to project
title: A graduate student's digital toolset
author: Chang-Yu Chang
date: '2020-08-05'
tags: 
  - digital tool
categories:
  - digital tool
summary: My list of digital tools that help productivity
output:
  blogdown::html_page:
    toc: true
    number_sections: false
    toc_depth: 2
---

```{r include = FALSE}
knitr::opts_chunk$set(eval = TRUE, collapse = TRUE, comment = NA, tidy = FALSE)
```


I have always been interested in digital tools that can potentially save my time from repetive tasks, maximize the use of idle time, reduce friction between tasks, and tame my monkey mind. I had a couple digital tools that I stick to before pandamic. But since lockdown due to covid-19 in early March, some digital tools have become less used in the past few months and some have become increasingly important in my research and life. 

Therefore, here you go this post. This post is more like a self-serving note than a aim-to-be useful technical article. If you hate multiple tabs, prefer a consise side dock, need to work among devices (PC/mobile), you may find this post helpful. 

NOTE: this is a working list of tools what I *currently* use, which means that I may update it if I find some thing interesting

# TL;DR

Who am I needing this list? A biology PhD student who transitioned from doing 80% benchwork to 100% computational work since lockdown.

Chrome works as my main working interface, which contains the following apps/services:

* Toggl for tracking time use
* Pocket for web-based article managements 
* Paperpile for academic reference management
* IFTTT for automation on connecting the applications
* Google office
* Extension: Workona to separate work-related to other tasks

I use Evernote to schedule, take notes, and collect information. 


# My rules of choosing app/software

I am intrinsically prone to boredom from tedious, repetitive tasks. Here are some principles I asked myself when choosing an app/software:

* Can it be launched in Google Chrome? 
* Can I use it across multiple devices (iPhone and Mac)? 
* Is the data stored on cloud?

These requirements have helped me saving time in the long run. If all applications can be opened in chrome, I can reduce the number of opening specific software. Accessibility across devices enables maximizing usage of idle time (for example, commuting). Cloud-based storage guarantees the progress in each app is up-to-dated across all devices.

# App/software list

In principle, all of them can launched in Chrome.

## Evernote

I take all my notes in Evernote. It serves as my inbox for collecting informations and to-do list management. It has amazing features like note links, tag system, and seamless cloud-based sync across devices. I also use Evernote to plan weekly schedule (with the idea of bullet journal), manage reading plans, and notes on cooking recipe etc. I love Evernote. The way to manage notebooks and naming notes is itself an art and still hard to learn, so it deserves a separate blog post.

But the con is also obvious. To enjoy some of the features above, you need to subscribe the professional plan which costs $XX/year. Evernote is free to use but limited up to 2GB storage for attachments like images and pdf.

## Chrome as the only working space

The idea is to reduce the number of distracting windows/softwares. I centralized almost all of works on Google Chrome if possible. Here are some advantages:

* Shortcuts. Cmd + Number (e.g., Cmd + 1) shifts to the first tab.
* Most apps that require sign-in allow link to Google account. 
* If I change devices, for instance from lab PC to my personal Macbook Pro, chrome sync in all my bookmarks and up-to-date progress in the background.
* Other google services (gmail, drive, doc, sheet, form, etc)

Essentially when I work, I only have five windows open at any time: Finder, Chrome, Evernote, Rstudio, and Terminal. If I am not coding, then the number reduces to three (Finder, Chrome and Evernote). Neat sidebar! 

As I rely more and more on Chrome for most tasks, the problem becomes how to manage the increasing tabs in Chrome. My fragile mind is easily distracted and irritated by many tabs.

Thanks to the amazing Chrome add-in [Workona](), which divides tabs into groups and save the groups. I arbitrarily group my tabs into tasks related to work, coding, and reading. Similar to the idea of separating the functions of rooms by physical space: bedroom for sleeping and living room for relaxing. 

Extensions
* Workona
* Adblock
* Paperpile (for literature management)
* Pocket (for collecting interesting articles)

## Toggl

Toggl is a time tracking app that simple records the time spent on a desk. It’s not a magic app (at least to my knowledge) that automatically starts to time when you initiate a task (like tabbing reading). I use it to track how long I have been focusing on a single task (for example, reading a paper or coding) 

## Pocket

Pocket saves article you find interesting online to view later. It can operate on iPhone and chrome. A great feature is that it remove the layout of the origial article and reduce it into only text, great for my monkey mind. Also very suitable for saving blog posts to read during commuting.

## Paperpile

Paperpile is a reference management app that works similarly to Mendeley, Endnote, Paper, or Zotero. I shifted from Mendeley to Paperpile because it works with Google Doc seamlessly and my lab uses Google doc for writing as well. Good features on Paperpile: chrome extension for collecting papers, chrome tab as main access, shortcut for pdf highlighting and noting (on chrome), backup on google drive. Perfectly fit in the chrome universe.

The disadvantage is clear. The subscription fee for Paperpile is $XX/year. Mendeley also works OK but it quickly hits the storage limit (2GB) for pdf. On top of that, Mendeley belongs to Elsevier. As a scientist there is clear reason I do not recommend it.  

## IFTTT

IFTTT lubricates the apps mentioned above. IFTTT stands for “IF This Then That”. It is like a robot always working in the background. For example, IF I like or retweet a tweet, THEN it save the first link in that tweet to my Pocket reading list. There is much more IFTTT can do.















