# Configuration
# Title of your site
title = "Chang-Yu Chang 張昌祐"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://www.changyuchang.name/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "&copy; Chang-Yu Chang, {year}"

# Enable comments by entering your Disqus shortname
disqusShortname = "changyuchang"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-132767541-1"

#theme = "starter-hugo-academic"

metaDataFormat = "yaml"
footnoteReturnLinkContents = "&#8617;" # ↩
# set deliberately low for testing choose your preffered number based on the blog layout you've chosen
paginate = 5
preserveTaxonomyNames = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
enableEmoji = true
